apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ${ENVIRONMENT}-${KUBE_SERVICE}
  namespace: ${ENVIRONMENT}-${KUBE_NAMESPACE}
spec:
  maxReplicas: ${MAX_REPLICA}
  minReplicas: ${MIN_REPLICA}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${ENVIRONMENT}-${KUBE_SERVICE}
  targetCPUUtilizationPercentage: 40
